String subPlan;
String dob;
String name;
String email;
String phone;
String emailOrNumVal;
String ins;
String pincode;
String photoUrl;
String group;
String uid;
bool isGLogin=false;
// String group;
